// Initial roles data for the RBAC system
export const initialRoles = [
  {
    name: 'admin',
    description: 'Full administrative access to all collections and features',
    privileges: [
      {
        collection: 'users',
        view: true,
        create: true,
        edit: true,
        delete: true,
        selfControl: false,
      },
      {
        collection: 'roles',
        view: true,
        create: true,
        edit: true,
        delete: true,
        selfControl: false,
      },
      {
        collection: 'universities',
        view: true,
        create: true,
        edit: true,
        delete: true,
        selfControl: false,
      },
      {
        collection: 'university-pages',
        view: true,
        create: true,
        edit: true,
        delete: true,
        selfControl: false,
      },
      {
        collection: 'students',
        view: true,
        create: true,
        edit: true,
        delete: true,
        selfControl: false,
      },
      {
        collection: 'courses',
        view: true,
        create: true,
        edit: true,
        delete: true,
        selfControl: false,
      },
      {
        collection: 'posts',
        view: true,
        create: true,
        edit: true,
        delete: true,
        selfControl: false,
      },
      {
        collection: 'media',
        view: true,
        create: true,
        edit: true,
        delete: true,
        selfControl: false,
      },
      {
        collection: 'categories',
        view: true,
        create: true,
        edit: true,
        delete: true,
        selfControl: false,
      },
      {
        collection: 'bookings',
        view: true,
        create: true,
        edit: true,
        delete: true,
        selfControl: false,
      },
    ],
  },
  {
    name: 'university-role',
    description: 'University users who can manage their own university and pages',
    privileges: [
      {
        collection: 'universities',
        view: true,
        create: false,
        edit: true,
        delete: false,
        selfControl: true,
      },
      {
        collection: 'university-pages',
        view: true,
        create: true,
        edit: true,
        delete: true,
        selfControl: true,
      },
      {
        collection: 'media',
        view: true,
        create: true,
        edit: true,
        delete: true,
        selfControl: true,
      },
      {
        collection: 'users',
        view: false,
        create: false,
        edit: false,
        delete: false,
        selfControl: false,
      },
      {
        collection: 'roles',
        view: false,
        create: false,
        edit: false,
        delete: false,
        selfControl: false,
      },
    ],
  },
  {
    name: 'editor',
    description: 'Content editors who can manage posts, media, and categories',
    privileges: [
      {
        collection: 'posts',
        view: true,
        create: true,
        edit: true,
        delete: true,
        selfControl: false,
      },
      {
        collection: 'media',
        view: true,
        create: true,
        edit: true,
        delete: true,
        selfControl: false,
      },
      {
        collection: 'categories',
        view: true,
        create: true,
        edit: true,
        delete: true,
        selfControl: false,
      },
      {
        collection: 'users',
        view: false,
        create: false,
        edit: false,
        delete: false,
        selfControl: false,
      },
      {
        collection: 'universities',
        view: false,
        create: false,
        edit: false,
        delete: false,
        selfControl: false,
      },
    ],
  },
  {
    name: 'post-editor',
    description: 'Limited role that can only manage posts',
    privileges: [
      {
        collection: 'posts',
        view: true,
        create: true,
        edit: true,
        delete: false,
        selfControl: false,
      },
      {
        collection: 'media',
        view: true,
        create: false,
        edit: false,
        delete: false,
        selfControl: false,
      },
      {
        collection: 'users',
        view: false,
        create: false,
        edit: false,
        delete: false,
        selfControl: false,
      },
    ],
  },
]